#!/bin/sh

OUTPUT_STYLE=${1:-compressed}

echo "node-sass with output-style of ${OUTPUT_STYLE}"

node-sass --output-style "${OUTPUT_STYLE}" --include-path node_modules/normalize-scss/sass src/scss --output src/assets/css;
